<p>CONTRATO DE LOCATÁRIO RESIDENCIAL</p>

<p>LOCADOR(A): <?php echo $dados['nome_locador'] ?>, RG: <?php echo $dados['rg_locador'] ?>-<?php echo $dados['orgao_exp_locador'] ?>/<?php echo $dados['uf_expedidor_locador'] ?> e do CPF: <?php echo $dados['cpf_locador'] ?>, <?php echo $dados['nacionalidade_locador'] ?>, <?php echo $dados['estado_civil_locador'] ?>, <?php echo $dados['profissao_locador'] ?>, residente e domiciliado nesta cidade <?php echo $dados['cidade_locador'] ?> - <?php echo $dados['estado_locador'] ?> na <?php echo $dados['endereco_locador'] ?>, N&ordm; <?php echo $dados['numero_locador'] ?>, <?php echo $dados['complemento_locador'] ?>, Bairro <?php echo $dados['bairro_locador'] ?>, CEP &ndash; <?php echo $dados['cep_locador'] ?>.</p>
<p>LOCATARIO(A)(S): Como principal pagador das mensalidades do aluguel e demais obriga&ccedil;&otilde;es constantes deste Contrato assina(m) o(a)(s) Sr.(a)(s) <b><?php echo $dados['nome_locatario']; ?></b>, RG: <b><?php echo $dados['rg_locatario'] ?>, <?php echo $dados['orgao_exp_locatario'] ?>/<?php echo $dados['uf_locatario'] ?></b> e do CPF: <b><?php echo $dados['cpf_locatario'] ?>, <?php echo $dados['nacionalidade_locatario'] ?>, <?php echo $dados['estado_civil_locatario'] ?>, <?php echo $dados['profissao_locatario'] ?></b>, residente e domiciliado nesta cidade de <?php echo $dados['cidade_locatario'] ?>-<?php echo $dados['estado_locatario'] ?> na, <b><?php echo $dados['endereco_locatario'] ?></b>, Bairro: <b><?php echo $dados['bairro_locatario'] ?></b>, CEP: <b><?php echo $dados['cep_locatario'] ?></b></p>

<p>FIADOR(A)(S): Como fiador(es) e principal(ais) pagador(es) das mensalidade do aluguel e demais obriga&ccedil;&otilde;es constantes deste Contrato , assina(m) o(a)(s) Sr.(a)(s) ____________________, RG: __________-SSP/___ e do CPF: ____________-___, ______________, ________________, _______________, residente e domiciliado nesta cidade de __________/__________ na ______________________, n&ordm; ___ , _________________, cuja garantia perdurar&aacute; na hip&oacute;tese de quaisquer reajustamentos ou prorroga&ccedil;&atilde;o, at&eacute; final satisfa&ccedil;&atilde;o das obriga&ccedil;&otilde;es oriundas da loca&ccedil;&atilde;o, renunciando expressamente o benef&iacute;cio de ordem de que tratam os artigos 827, 828 e 829 do C&oacute;digo Civil Brasileiro.</p>

<p>PAR&Aacute;GRAFO &Uacute;NICO: O LOCAT&Aacute;RIO e o(s) FIADOR(ES) outorgam irrevog&aacute;vel m&uacute;tua e reciprocamente poderes para receber CITA&Ccedil;&Otilde;ES, NOTIFICA&Ccedil;&Otilde;ES ou INTIMA&Ccedil;&Otilde;ES que ser&atilde;o feitas mediante correspond&ecirc;ncias com aviso de recebimento, tratando-se de pessoa f&iacute;sica e jur&iacute;dica, tamb&eacute;m fax-s&iacute;mile, ou ainda, se necess&aacute;rio, pelas demais formas previstas no C&oacute;digo de Processo Civil.</p>
<p>I OBJETO</p>
<p>CL&Aacute;USULA PRIMEIRA: O objeto do presente contrato &eacute; a loca&ccedil;&atilde;o do im&oacute;vel localizado na <?php echo $dados['endereco_imovel'] ?>, Quitinete <b><?php echo $dados['imovel'] ?></b>, <?php echo $dados['complemento_imovel'] ?>, Bairro <?php echo $dados['bairro_imovel'] ?>, CEP &ndash; <?php echo $dados['cep_imovel'] ?>.</p>
<p>II &ndash; DESTINA&Ccedil;&Atilde;O </p>
<p>CL&Aacute;USULA SEGUNDA: O(A) LOCAT&Aacute;RIO(A) utilizar&aacute; o im&oacute;vel exclusivamente para fins residenciais do(a) Sr.(a) <b><?php echo $dados['nome_locatario'] ?></b> e seus familiares, destino que n&atilde;o poder&aacute; ser alterado sem o pr&eacute;vio consentimento escrito do(a) LOCADOR(A), sendo vedada qualquer cess&atilde;o, transfer&ecirc;ncia ou subloca&ccedil;&atilde;o, ainda quando parcial e tempor&aacute;ria, gratuita ou onerosa.</p>
<p>CL&Aacute;USULA TERCEIRA: Ser&aacute; equiparada a viola&ccedil;&atilde;o da Cl&aacute;usula anterior, qualquer situa&ccedil;&atilde;o de fato pela qual o(a) LOCAT&Aacute;RIO(A) deixe de ocupar direta e integralmente o im&oacute;vel locado, em seu nome e conta própria.</p>
<p>III &ndash; PRAZO</p>
<p>CL&Aacute;USULA QUARTA: A loca&ccedil;&atilde;o ser&aacute; pelo prazo determinado de <b><?php echo $dados['prazo'] ?> (<?php echo $dados['prazo_extenso'] ?> mes (es))</b> , contando-se esse per&iacute;odo de <b><?php echo $dados['data_inicio'] ?></b> a terminar no dia <b><?php echo $dados['data_fim'] ?></b>, data em que o(a) locat&aacute;rio(a) obriga-se a restituir o im&oacute;vel completamente desocupado, em conformidade com a LEI N&ordm; 8.245 (LEI DO INQUILINATO) e MEDIDA PROVIS&Oacute;RIA n&ordm; 482 de 30/03/94.</p>
<p>CL&Aacute;USULA QUINTA: Se o LOCAT&Aacute;RIO(A) devolver o im&oacute;vel antes de transcorrido o prazo estabelecido na cl&aacute;usula anterior ou a rescis&atilde;o ocorrer por inadimplemento de obriga&ccedil;&atilde;o aqui ajustada, pagará uma multa contratual correspondente a 03 (tr&ecirc;s) meses de aluguel, sem preju&iacute;zo do integral cumprimento das demais san&ccedil;&otilde;es legais e contratuais. (Artigo 4&ordm;, da Lei n&ordm; 8.245/91..</p>
<p>PAR&Aacute;GRAFO &Uacute;NICO: O(A) LOCAT&Aacute;RIO(A) ficar&aacute; dispensado da multa contratual se a devolu&ccedil;&atilde;o do im&oacute;vel decorrer de transfer&ecirc;ncia pelo seu empregador para prestar servi&ccedil;os em, localidades diversas daquela do in&iacute;cio do contrato ou, se notificar por escrito ao(&agrave;) LOCADOR(A) ou seu representante legal, ap&oacute;s decorridos 12 (doze) meses de aluguel, com o prazo de no m&iacute;nimo 30 (trinta) dias de anteced&ecirc;ncia.</p>
<p>CL&Aacute;USULA SEXTA: Findo o prazo de loca&ccedil;&atilde;o estipulado na Cl&aacute;usula Quarta, se n&atilde;o ocorrer a hip&oacute;tese de rescis&atilde;o ou a da ren&uacute;ncia , o que neste &uacute;ltimo caso dever&aacute; ocorrer mediante aviso por escrito de qualquer dos contratantes ao outro at&eacute; trinta (30) dias antes de se vencer cada per&iacute;odo contratual, prorrogar-se-&aacute; a loca&ccedil;&atilde;o, consoante a assinatura de um novo contrato, com garantia consoante deste contrato.</p>
<p>IV – PREÇO</p>
<p>CLÁUSULA SÉTIMA: O aluguel mensal é de <b><?php echo number_format($dados['valor'], 2, ',', '.') ?> (<?php echo $dados['valor_extenso'] ?>)</b> com REAJUSTE EM COMUM ACORDO ENTRE AS PARTES ou  pelos índices oficiais do governo federal  no período acumulativamente ou outro índice oficial determinado pelo governo que venha à  substituí-lo. Daí­ por diante, caso ocorra a hipótese prevista na cláusula Sexta, ficará sujeito a reajustamentos periódicos estabelecidos na legislação pertinente que estiver em vigor.</p>
<p>CLÁUSULA OITAVA:– O aluguel será pago pontualmente até o dia <b>2 (dois)</b> de cada mês de locação ajustada na cláusula quarta deste instrumento, independente de cobrança, no Escritório Imobiliário (nome do(a) corretor(a) ou imobiliária – cite o endereço completo), ou onde o(a) LOCADOR(A) determinar, estendendo-se esse prazo para o primeiro dia útil seguinte, caso coincida com sábado, domingo ou  feriado. Ultrapassando o dia acima estipulado, o aluguel será acrescido de multa de 2% (dois por cento) ao mês a partir do primeiro dia útil do vencimento e mais 0,3%  (zero virgula três por cento) de juros de mora, ao dia.</p>
<p>PARÁGRAFO ÚNICO: É FACULTADO AO LOCATÁRIO(A) conceder desconto de R$ 20,00 sobre o valor do aluguel mensal ao LOCADOR(A) que efetuar o pagamento do aluguel até a data do seu vencimento, condicionando-se tal desconto ao pagamento da conta de luz do mês subsequente na referida data do vencimento.</p>
<p>CLAUSULA NONA: Se o LOCADOR(A), ou seu representante legal,   recusar o recebimento sem justa causa ou o LOCATÁRIO(A) tiver dificuldade em efetuar o pagamento das obrigações contratuais, deverá este(a) promover o respectivo depósito judicial até o 5º(quinto) dia útil do mês subsequente ao vencido. Não o fazendo, entender-se-á que ficou constituído em mora, para todos os efeitos legais, especialmente para a incidência das obrigações adiante convencionadas.</p>
<p>CLÁUSULA DÉCIMA: O aluguel será inteiramente liquido ao(à) LOCADOR(A), respeitada a legislação sobre a renda, correndo por conta exclusiva do(a) LOCATÁRIO(A):</p>
<p>a) – Despesas de força e luz, cuja unidade consumidora, é <b>UC - <?php echo $dados['uc']?></b> e serviços semelhantes, além das despesas ordinárias de condomínio, se for o caso. Os comprovantes dos pagamentos deverão ser entregues ao(à) LOCADOR(A) , ou seu representante legal, junto com o pagamento do aluguel vencido, no prazo da locação estipulado neste instrumento ou provável prorrogação;</p>
<p>b) – Pagamento do Imposto Predial e Territorial Urbano(IPTU), além das taxas municipais relativas ao imóvel locado. Os comprovantes de pagamentos deverão ser entregues ao(à) LOCADOR(A) , ou seu representante legal, junto com o pagamento do aluguel vencido, no prazo da locação estipulado neste instrumento ou provável prorrogação;</p>
<p>c) Satisfação de todas as exigências do poder público, relativas ao imóvel locado.</p>
<p>CLÁUSULA DÉCIMA PRIMEIRA: Além das obrigações mencionadas, qualquer outra que caiba ao (à) LOCATÁRIO(A) e for paga pelo(a) LOCADOR(A) , poderá este (a) também cobrá-la junto e indissoluvelmente  com qualquer aluguel subsequente , aplicando-se à demora ou à recusa de ressarcimento, as mesmas sanções que decorreriam do atraso no pagamento dos aluguéis.</p>
<p>CLÁUSULSA DÉCIMA SEGUNDA:– Obriga-se o(a) LOCATÁRIO(A) a remeter ao(à)  LOCADOR(A), ou seu representante legal, dentro das 24 (vinte e quatro) horas de seu recebimento, qualquer correspondência, intimação ou notificação que lhe for dirigida sobre o imóvel locado, e, caso não o faça, assume integralmente todas as responsabilidades pelas obrigações exigidas em tais intervenções e suas consequências.</p>
<p>CLÁUSULA DÉCIMA TERCEIRA: Obriga-se o(a) LOCATÁRIO(A) a cumprir o regulamento interno do condomínio, quando for o caso,  assumindo toda e qualquer  responsabilidade com os danos causados a terceiros, não lhe sendo permitido ocupar as áreas comuns, como corredores e escadas, sendo proibido manter cães ou outros animais em qualquer dependência do prédio locado.</p>
<p>CLÁUSULA DÉCIMA QUARTA: No ato da entrega das chaves o(a) LOCATÁRIO(A) liquidará os aluguéis até àquela data e apresentará os comprovantes quitados das despesas de que trata a Cláusula Décima, e depositará, mediante recibo, a importância correspondente ao consumo de energia, água e taxa de condomínio e demais despesas dos dias que excederem o último talão quitado, calculado à base do valor médio dos 03 (três) meses anteriores.</p>
<p>V – CONSERVAÇÃO</p>
<p>CLÁUSULA DÉCIMA QUINTA: Obriga-se o(a) LOCATÁRIO(A) a devolver o imóvel  no estado em que o recebe, de acordo com o Laudo de Vistoria em anexo, que passa a fazer parte integrante deste Contrato.</p>
<p>CLÁUSULA DÉCIMA SEXTA: O(A) LOCATÁRIO(A) satisfará à própria custa, com solidez e perfeição, todos os reparos e consertos de que necessite ou venha a necessitar o imóvel locado, satisfazendo, nesse sentido, todas e quaisquer exigências das autoridades públicas.</p>
<p>CLÁUSULA DÉCIMA SÉTIMA: O(A) LOCATÁRIO(A) será responsável pelos danos causados ao imóvel pelo mau trato ou por aqueles que resultarem para os vizinhos do mau uso do imóvel locado, não se prejudicando, durante os respectivos reparos, a continuidade deste contrato, em todos os seus efeitos.</p>
<p>CLÁUSULA DÉCIMA OITAVA: O(A) LOCADOR(A) ou seu representante legal, poderá inspecionar o imóvel, pessoalmente, ou através de representantes, sendo tal vistoria imprescindível antes da restituição, a fim de verificar a fiel observância das obrigações assumidas pelo(a) LOCATÁRIO(A) neste contrato, o(a) qual não poderá, sob pretexto algum, fazer oposição a esse direito.</p>
<p>CLÁUSULA DÉCIMA NONA: As benfeitorias ou acessões que vierem a ser introduzidas, de qualquer natureza, aderirão automaticamente ao imóvel locado, integrando a plena propriedade do(a) LOCADOR(A) . O consentimento escrito do LOCADOR(A), ou seu representante legal, todavia, será imprescindível. O LOCATÁRIO(A) renuncia desde logo, irrevogavelmente, a todo direito de indenização, compensação ou  retenção, relativo aos valores despendidos.</p>
<p>CLÁUSULA VIGÉSIMA: As adaptações que se fizerem necessárias à instalação de aparelhos eletrodomésticos, inclusive ar-condicionado, e que prescindam de mutilar o imóvel, poderão ser efetuados mediante prévio consentimento do(a) LOCADOR(A), ou seu representante legal, sempre por escrito.</p>
<p>VI – SANÇÕES</p>
<p>CLÁUSULA VIGÉSIMA PRIMEIRA: Ao inadimplemento total ou parcial de qualquer das obrigações deste contrato, serão aplicadas cumulativamente ou alternativamente, a juízo do(a) LOCADOR(A), ou seu representante legal, as seguintes sanções:</p>
<p>a) Rescisão contratual automática, independentemente de interpelação judicial ou extrajudicial, não significando a tolerância de qualquer infração como renúncia deste direito, caso a mesma se repita ou se prolongue, com exigência das obrigações financeiras totais previstas neste contrato, por antecipação;</p>
<p>b) Multa penal igual ao valor do dano, em se tratando de desconservação do imóvel e suas benfeitorias;</p>
<p>c) Perdas e danos que se apurarem, incluindo custos processuais;</p>
<p>d) Pagamentos dos honorários dos advogados e peritos do(a) LOCADOR(A), ou seu representante legal, desde já fixado em 20% (vinte por cento) se for litigioso e 10% (dez por cento) se for amigável.</p>
<p>CLÁUSULA VIGÉSIMA SEGUNDA: As partes contratantes elegem o foro da Comarca de São Luis, Estado do Maranhão , para dirimir quaisquer dúvidas oriundas deste Contrato, renunciando a qualquer outro, por mais privilegiado que seja.</p>
<p>E por estarem justos e contratados, assinam o presente contrato em 03 (três) vias de igual teor e forma, na presença de 02 (duas) testemunhas que também assinam, elegendo o Foro da Comarca de São Luis/Ma, para qualquer ação oriunda deste contrato.</p>



<p>São luis, ..... de ............ de 20..... </p>

<p>Locador _____________________________</p>

<p>Locatário:____________________________</p>

<p>Fiadores:_____________________________</p>

<p>Testemunhas:</p>

<p>Nome:_____________________________  RG_________________- _________</p>

<p>Nome:______________________________</p>

<p> RG:_________________- _________</p>

